version: '3.8'
name: simple-axum-google-oauth

services:
  backend:
    container_name: backend
    build: .
    command: > 
      sh -c
      "apt-get update                                            && \
       apt-get upgrade -y                                        && \
       curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
       apt-get install -y nodejs && npm install -g npm           && \
       cargo prisma generate                                     && \
       cargo prisma migrate dev --name production                && \
       cargo prisma migrate deploy                               && \
       cargo build  --release                                    && \
       cargo run    --release                                     & \
       npx -y prisma studio"
    volumes:
      - type: bind
        source: ./.env
        target: /app/.env
        read_only: true
    ports:
      - '5000:5000'
      - '5555:5555'
    depends_on:
      - postgres
    networks:
      - local
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: password
      POSTGRES_DB: local
    ports:
      - '5432:5432'
    networks:
      - local
networks:
  local: